syntax="proto3";

package streaming;

option go_package = "github.com/orlandorode97/grpc-stuff/module3/exercise/proto";

service FileUploadService {
  rpc DownloadFile(DownloadFileRequest) returns (stream DownloadFileResponse);
  rpc UploadFile(stream UploadFileRequest) returns (UploadFileResponse);
  rpc GetListOfFiles(GetListOfFilesRequest) returns (GetListOfFilesResponse);
}

message DownloadFileRequest {
  string name = 1;
}

message DownloadFileResponse {
  bytes content = 1;
}

message UploadFileRequest {
  bytes content = 1;
}

message UploadFileResponse {
  string name = 1;
}

message GetListOfFilesRequest {}

message GetListOfFilesResponse {
  repeated string files = 1;
}
