// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/hello.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LongRunningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LongRunningRequest) Reset() {
	*x = LongRunningRequest{}
	mi := &file_proto_hello_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LongRunningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongRunningRequest) ProtoMessage() {}

func (x *LongRunningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongRunningRequest.ProtoReflect.Descriptor instead.
func (*LongRunningRequest) Descriptor() ([]byte, []int) {
	return file_proto_hello_proto_rawDescGZIP(), []int{0}
}

type LongRunningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LongRunningResponse) Reset() {
	*x = LongRunningResponse{}
	mi := &file_proto_hello_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LongRunningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LongRunningResponse) ProtoMessage() {}

func (x *LongRunningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LongRunningResponse.ProtoReflect.Descriptor instead.
func (*LongRunningResponse) Descriptor() ([]byte, []int) {
	return file_proto_hello_proto_rawDescGZIP(), []int{1}
}

type FlakyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlakyRequest) Reset() {
	*x = FlakyRequest{}
	mi := &file_proto_hello_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlakyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlakyRequest) ProtoMessage() {}

func (x *FlakyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlakyRequest.ProtoReflect.Descriptor instead.
func (*FlakyRequest) Descriptor() ([]byte, []int) {
	return file_proto_hello_proto_rawDescGZIP(), []int{2}
}

type FlakyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlakyResponse) Reset() {
	*x = FlakyResponse{}
	mi := &file_proto_hello_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlakyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlakyResponse) ProtoMessage() {}

func (x *FlakyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlakyResponse.ProtoReflect.Descriptor instead.
func (*FlakyResponse) Descriptor() ([]byte, []int) {
	return file_proto_hello_proto_rawDescGZIP(), []int{3}
}

type GetServerAddressRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerAddressRequest) Reset() {
	*x = GetServerAddressRequest{}
	mi := &file_proto_hello_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerAddressRequest) ProtoMessage() {}

func (x *GetServerAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerAddressRequest.ProtoReflect.Descriptor instead.
func (*GetServerAddressRequest) Descriptor() ([]byte, []int) {
	return file_proto_hello_proto_rawDescGZIP(), []int{4}
}

type GetServerAddressResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerAddressResponse) Reset() {
	*x = GetServerAddressResponse{}
	mi := &file_proto_hello_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerAddressResponse) ProtoMessage() {}

func (x *GetServerAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hello_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerAddressResponse.ProtoReflect.Descriptor instead.
func (*GetServerAddressResponse) Descriptor() ([]byte, []int) {
	return file_proto_hello_proto_rawDescGZIP(), []int{5}
}

func (x *GetServerAddressResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_proto_hello_proto protoreflect.FileDescriptor

const file_proto_hello_proto_rawDesc = "" +
	"\n" +
	"\x11proto/hello.proto\x12\x05hello\"\x14\n" +
	"\x12LongRunningRequest\"\x15\n" +
	"\x13LongRunningResponse\"\x0e\n" +
	"\fFlakyRequest\"\x0f\n" +
	"\rFlakyResponse\"\x19\n" +
	"\x17GetServerAddressRequest\"4\n" +
	"\x18GetServerAddressResponse\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress2\xdd\x01\n" +
	"\fHelloService\x12D\n" +
	"\vLongRunning\x12\x19.hello.LongRunningRequest\x1a\x1a.hello.LongRunningResponse\x122\n" +
	"\x05Flaky\x12\x13.hello.FlakyRequest\x1a\x14.hello.FlakyResponse\x12S\n" +
	"\x10GetServerAddress\x12\x1e.hello.GetServerAddressRequest\x1a\x1f.hello.GetServerAddressResponseB3Z1github.com/orlandorode97/grpc-stuff/module6/protob\x06proto3"

var (
	file_proto_hello_proto_rawDescOnce sync.Once
	file_proto_hello_proto_rawDescData []byte
)

func file_proto_hello_proto_rawDescGZIP() []byte {
	file_proto_hello_proto_rawDescOnce.Do(func() {
		file_proto_hello_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hello_proto_rawDesc), len(file_proto_hello_proto_rawDesc)))
	})
	return file_proto_hello_proto_rawDescData
}

var file_proto_hello_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_hello_proto_goTypes = []any{
	(*LongRunningRequest)(nil),       // 0: hello.LongRunningRequest
	(*LongRunningResponse)(nil),      // 1: hello.LongRunningResponse
	(*FlakyRequest)(nil),             // 2: hello.FlakyRequest
	(*FlakyResponse)(nil),            // 3: hello.FlakyResponse
	(*GetServerAddressRequest)(nil),  // 4: hello.GetServerAddressRequest
	(*GetServerAddressResponse)(nil), // 5: hello.GetServerAddressResponse
}
var file_proto_hello_proto_depIdxs = []int32{
	0, // 0: hello.HelloService.LongRunning:input_type -> hello.LongRunningRequest
	2, // 1: hello.HelloService.Flaky:input_type -> hello.FlakyRequest
	4, // 2: hello.HelloService.GetServerAddress:input_type -> hello.GetServerAddressRequest
	1, // 3: hello.HelloService.LongRunning:output_type -> hello.LongRunningResponse
	3, // 4: hello.HelloService.Flaky:output_type -> hello.FlakyResponse
	5, // 5: hello.HelloService.GetServerAddress:output_type -> hello.GetServerAddressResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_hello_proto_init() }
func file_proto_hello_proto_init() {
	if File_proto_hello_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hello_proto_rawDesc), len(file_proto_hello_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hello_proto_goTypes,
		DependencyIndexes: file_proto_hello_proto_depIdxs,
		MessageInfos:      file_proto_hello_proto_msgTypes,
	}.Build()
	File_proto_hello_proto = out.File
	file_proto_hello_proto_goTypes = nil
	file_proto_hello_proto_depIdxs = nil
}
